name: Get latest COVID-19 stats

on:
  schedule:
    - cron: '25 02 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Get latest COVID-19 stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest UK stats
        run: |
          wget -O "$GITHUB_WORKSPACE/covid-uk.json" --compression=auto 'https://coronavirus.data.gov.uk/api/v1/data?filters=areaType=overview&structure={%22date%22:%22date%22,%22newCasesByPublishDate%22:%22newCasesByPublishDate%22,%22newAdmissions%22:%22newAdmissions%22,%22newPeopleVaccinatedFirstDoseByPublishDate%22:%22newPeopleVaccinatedFirstDoseByPublishDate%22,%22newPeopleVaccinatedSecondDoseByPublishDate%22:%22newPeopleVaccinatedSecondDoseByPublishDate%22,%22newDeaths28DaysByPublishDate%22:%22newDeaths28DaysByPublishDate%22}&format=json'
          git add covid-uk.json
          git -c user.name='GitHub Actions auto-commit' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m 'Latest UK stats.'
          git push
